language: android
android:
  components:
  - build-tools-27.0.3
  - android-25
  - tools
  - platform-tools
  - tools
  - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"